config/routes.rb
Rails.application.routes.draw do
  root 'polls#index'

  get 'healthz' => 'application#healthz'

  resources :polls, only: :index do
    post :vote, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  ## Associations
  has_many :options, class_name: 'PollOption'
  has_many :votes

  def vote_for(option, ip)
    votes.create(poll_option: option, ip: ip)
  end

  class << self
    def stats
      sql = <<-SQL
        SELECT p.id, p.poll_id, 
          (SELECT COUNT(*) FROM votes WHERE votes.poll_option_id = p.id)::int * 100.0 / 
          (SELECT COUNT(*) FROM votes WHERE votes.poll_id = p.poll_id)::int
        FROM poll_options AS p
        right join votes using(poll_id)
      SQL

      connection.select_all(sql).rows.each_with_object({}) do |result,hash|
        option_id, poll_id, score = result
        hash[[poll_id, option_id]] = Float(score).round
      end
    end
  end
end

app/models/poll_option.rb
class PollOption < ApplicationRecord
  ## Associations
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  ## Associations
  belongs_to :poll_option
  belongs_to :poll

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def healthz
    head(:ok)
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :load_poll, only: :vote

  # GET /polls
  def index
    @polls = Poll.all.includes(options: [:votes])
    @stats = Poll.stats
  end

  # POST /polls/:id/vote.json
  def vote
    @form = VotePollForm.new(poll_parameters)

    if @form.save
      respond_to do |format|
        format.json { head :created }
        format.js
      end
    else
      respond_to do |format|
        format.json { render json: @form.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  private

  def load_poll
    @poll = Poll.find(params[:id])
  end

  def poll_parameters
    params.slice(:option_id).merge(poll: @poll, ip: request.remote_ip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def voted_at(poll)
    ip = request.remote_ip
    vote = poll.options.map(&:votes).flatten.detect{ |vote| vote.ip == ip }
    vote.created_at.to_s(:long) if vote
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poll Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    Your IP address: <b><%=request.remote_ip %></b>
    <%= yield %>
  </body>
</html>

app/views/polls/_option_list.erb
<% if options %>
  <ul class="list-group">
    <% options.each do |option| %>
      <li class="list-group-item">
        <div class="radio">
          <label>
            <input type="radio" name="option_id" value="<%=option.id%>">
            <%= option.name %>
          </label>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/polls/_poll_form.erb
<%=form_for poll, url: vote_poll_path(poll), remote: true, method: :post do |f| %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">
        <span class="glyphicon glyphicon-arrow-right"></span><%=poll.name %>
      </h3>
    </div>

    <div class="poll-options">
      <div class="panel-body">
        <%= render template: 'polls/_option_list', locals: { options: poll.options } %>
      </div>
      <div class="panel-footer">
        <%=f.submit 'Vote', class: 'btn btn-primary btn-sm'%>
        <span class="ajax-response" id="response-<%=poll.id%>"></span>
      </div>
    </div>
  </div>
<% end %>

app/views/polls/_poll_stat.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      <span class="glyphicon glyphicon-arrow-right"></span><%=poll.name %>
    </h3>
  </div>

  <div class="poll-options">
    <div class="panel-body">
      <br />
      <% poll.options.each do |option| %>
        <div class="progress">
          <div class="col-md-2"> <%= option.name %></div>
          <div class="col-md-6">
            <div class="progress-bar progress-bar-success" role="progressbar" style="min-width: 2em; width: <%=stats[[poll.id, option.id]] || 0%>%;">
              <%=stats[[poll.id, option.id]] || 0%>%
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="panel-footer">
      You voted at <strong><%=voted_at(poll)%></strong>
    </div>
  </div>
</div>

app/views/polls/index.erb
<div class="container">
  <div class="row">
      <% @polls.each do |poll|%>
        <div id="poll-item-<%=poll.id%>">
          <% if voted_at(poll) %>
            <%= render template: 'polls/_poll_stat', locals: { poll: poll, stats: @stats } %>
          <% else %>
            <%= render template: 'polls/_poll_form', locals: { poll: poll } %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/polls/vote.js.erb
<% if @form.success %>
  id = '#poll-item-<%=@form.poll.id%>'
  response = "<%= j (render template: 'polls/_poll_stat', locals: { poll: @form.poll, stats: Poll.stats }) %>"
  $(id).html(response)
  $(id + ' .poll-options').show()
<% else %>
  id = '#response-<%=@form.poll.id%>'
  response = '<%=@form.errors.full_messages.join(' ')%>'
  $(id).addClass('ajax-response-fail')
  $(id).text(response)
  $(id).show()
<% end%>